#!/usr/bin/env php
<?php

// Si no quieres configurar los permisos de la manera convencional sólo
// quita el comentario de la siguiente línea PHP
//umask(0000);
// lee http://gitnacho.github.com/symfony-docs-es/book/installation.html#instalando-y-configurando-symfony
// para más información

set_time_limit(0);

require_once __DIR__.'/bootstrap.php.cache';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->run();
